# Generated by Django 2.2.12 on 2020-04-30 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='name',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='customtext_name', to='home.CustomText'),
        ),
    ]
